# Generated by Django 3.1.7 on 2021-03-07 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://www.google.com/imgres?imgurl=https%3A%2F%2Ftoppng.com%2Fuploads%2Fpreview%2Fclipart-free-seaweed-clipart-draw-food-placeholder-11562968708qhzooxrjly.png&imgrefurl=https%3A%2F%2Ftoppng.com%2Fclipart-free-seaweed-clipart-draw-food-placeholder-PNG-free-PNG-Images_183132&tbnid=Q8g5eFdEpaSJUM&vet=12ahUKEwiyj_v5up7vAhUQtioKHSl9AcIQMygAegUIARCsAQ..i&docid=GUQIKMIQwRMTbM&w=840&h=859&q=placeholder%20food%20images&ved=2ahUKEwiyj_v5up7vAhUQtioKHSl9AcIQMygAegUIARCsAQ', max_length=500),
        ),
    ]
