# Generated by Django 3.1.7 on 2021-03-07 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_auto_20210307_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://www.theaxebraughing.uk/wp-content/uploads/2020/04/food-placeholder-image.jpg', max_length=500),
        ),
    ]
